<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wyrm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wyrm.DAL\Wyrm.DAL.csproj" />
  </ItemGroup>

</Project>
